Instalacion de sqlalchemy

In [1]:
!pip3 install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in /usr/lib/python3/dist-packages (1.4.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/lib/python3/dist-packages (from sqlalchemy) (1.1.2)

Importación de las librerías necesarias:

In [2]:
import pandas as pd
from sqlalchemy import create_engine

import pandas as pd: Importa la librería Pandas.

from sqlalchemy import create_engine: Importa la función create_engine de SQLAlchemy, que se utiliza para establecer la conexión con la base de datos.

Conexión a la Base de Datos SQLite con SQLAlchemy:

create_engine crea un objeto de "motor" que representa la conexión a la base de datos.

Conexión a la base de datos SQLite (asumiendo que el archivo de la base de datos se llama ecommerce.sqlite y está en el mismo directorio):

In [3]:
# Creamos un motor para la base de datos SQLite
engine = create_engine('sqlite:///ecomerce.sqlite')

# Probamos la conexión (opcional)
with engine.connect() as connection:
    print("Conexión a la base de datos exitosa.")

Conexión a la base de datos exitosa.

In [4]:
#Voy a listar las tablas de la base de datos
query = ''' 
            SELECT name 
            FROM sqlite_master 
            WHERE type = 'table' 
            ORDER BY name;
        '''
df_tablas = pd.read_sql_query(query, engine)

In [5]:
df_tablas

                                 name
0                           customers
1                         geolocation
2                        leads_closed
3                     leads_qualified
4                         order_items
5                      order_payments
6                       order_reviews
7                              orders
8   product_category_name_translation
9                            products
10                            sellers

create_engine('sqlite:///ecommerce.sqlite'): Crea un objeto engine que sabe cómo comunicarse con una base de datos SQLite ubicada en el archivo ecommerce.sqlite. La sintaxis 'sqlite:///' indica una base de datos SQLite local.

engine.connect(): Establece una conexión con la base de datos. Es importante cerrar la conexión después de usarla, y el with statement se encarga de esto automáticamente.

Ejecución de Consultas SQL Básicas con SQLAlchemy:

Introducción a las consultas SQL SELECT, FROM, WHERE, LIMIT.

Ejemplo 1: Seleccionar todas las columnas de la tabla customers y mostrar las primeras 5 filas usando Pandas:

In [ ]:
#INSPECCIONAMOS LAS COLUMNAS
# Ejecutamos una consulta SQL para seleccionar todos los clientes
query = ''' 
           SELECT * 
           FROM customers 
           LIMIT 5
        '''

# Leemos el resultado de la consulta directamente en un DataFrame de Pandas
df_customers = pd.read_sql(query, engine)

# Mostramos el DataFrame
print("Primeras 5 filas de la tabla 'customers':")
print(df_customers)

Primeras 5 filas de la tabla 'customers':
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

In [7]:
df_customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
#PARA VER EL NUMERO DE FILAS
query = ''' 
            SELECT COUNT(1)
            FROM customers
        '''
pd.read_sql_query(query, engine)

   COUNT(1)
0     99441

In [ ]:
#EJERCICIO: INSPECCIONAR TODAS LAS TABLAS

query = "SELECT * FROM customers LIMIT 5": Define una cadena de texto que contiene la consulta SQL. SELECT * selecciona todas las columnas de la tabla customers, y LIMIT 5 restringe el resultado a las primeras 5 filas.

pd.read_sql(query, engine): Función de Pandas que ejecuta la consulta SQL (query) utilizando la conexión a la base de datos (engine) y carga el resultado en un DataFrame llamado df_customers.

Ejemplo 2: Seleccionar columnas específicas y filtrar por una condición (usando la tabla orders):

In [9]:
#FILTROS
# Seleccionamos order_id, customer_id y order_status de la tabla orders
query_orders =  '''
                SELECT order_id, customer_id, order_status 
                FROM orders 
                WHERE order_status = 'delivered' 
                LIMIT 10
                '''
df_delivered_orders = pd.read_sql(query_orders, engine)
print("\nPrimeras 10 órdenes con estado 'delivered':")
print(df_delivered_orders)

Primeras 10 órdenes con estado 'delivered':
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
5  a4591c265e18cb1dcee52889e2d8acc3  503740e9ca751ccdda7ba28e9ab8f608
6  6514b8ad8028c9f2cc2374ded245783f  9bdf08b4b3b52b5526ff42d37d47f222
7  76c6e866289321a7c93b82b54852dc33  f54a9f0e6b351c431402b8461ea51999
8  e69bfb5eb88e0ed6a785585b27e16dbf  31ad1d1b63eb9962463f764d4e6e0c9d
9  e6ce16cb79ec1d90b1da9085a6118aeb  494dded5b201313c64ed7f100595b95c

  order_status
0    delivered
1    delivered
2    delivered
3    delivered
4    delivered
5    delivered
6    delivered
7    delivered
8    delivered
9    delivered

WHERE order_status = 'delivered': Cláusula SQL que filtra las filas donde la columna order_status es igual a 'delivered'.

Ejemplo 3: Seleccionar datos de la tabla products y ordenar por nombre:

In [ ]:
query_products = '''
                    SELECT  product_id, 
                            product_category_name, 
                            product_name_lenght 
                    FROM products
                    WHERE product_category_name <> 'None'
                    ORDER BY product_name_lenght 
                    LIMIT 5
                ''' 
# Mostramos el DataFrame
print("Primeras 5 filas de la tabla 'customers':")
print(df_customers)
df_long_products = pd.read_sql(query_products, engine)
print("\nLos 5 productos con el nombre más largo:")
print(df_long_products)

Los 5 productos con el nombre más largo:
                         product_id product_category_name  product_name_lenght
0  95e25af33821b9d231e06f1e7cd34d4e      moveis_decoracao                  5.0
1  84d0969ab5317ca361e0a628948a4624      moveis_decoracao                  5.0
2  3adb4888b6e99ae73176ac7979dc03a0      moveis_decoracao                  6.0
3  9b68d637bcc8963e7b736f9de0a4532f                 bebes                  7.0
4  4b23856b5ce1e62e9c09c7b952cfd9cf                 bebes                  7.0

ORDER BY product_name_lenght DESC: Cláusula SQL que ordena los resultados por la columna product_name_lenght en orden descendente (DESC).

Análisis Básico con Pandas de los Datos Extraídos:

Utilizar los DataFrames creados (df_customers, df_delivered_orders, df_long_products) para realizar análisis básicos como:

.head() y .info() para inspeccionar los DataFrames.
.value_counts() en columnas específicas para ver la distribución de valores.

.describe() para obtener estadísticas descriptivas (si las columnas son numéricas).

Filtrado básico en los DataFrames usando la sintaxis de Pandas.

In [ ]:
print("\nInformación del DataFrame de clientes:")
print(df_customers.info())

print("\nConteo de los diferentes estados de orden:")
query_order_status = "SELECT order_status FROM orders"
df_order_status = pd.read_sql(query_order_status, engine)
print(df_order_status['order_status'].value_counts())

print("\Estadísticas descriptivas de la longitud del nombre de los productos:")
query_product_length = "SELECT product_name_lenght FROM products"
df_product_length = pd.read_sql(query_product_length, engine)
print(df_product_length.describe())

# Filtrar clientes del estado de 'SP' usando Pandas
sp_customers = df_customers[df_customers['customer_state'] == 'SP']
print("\nPrimeros 5 clientes del estado de SP:")
print(sp_customers.head())

Ejercicios para el Estudiante:

Escribe una consulta SQL para seleccionar las primeras 10 filas de la tabla order_payments, incluyendo todas las columnas. Carga el resultado en un DataFrame de Pandas y muestra las primeras filas.
Escribe una consulta SQL para encontrar los diferentes tipos de pago (payment_type) en la tabla order_payments. Carga el resultado en un DataFrame y utiliza Pandas para mostrar los valores únicos de la columna payment_type.

Escribe una consulta SQL para seleccionar el customer_id y la customer_city de la tabla customers donde la ciudad sea 'sao paulo'. Carga el resultado en un DataFrame y muestra las primeras 5 filas.

(Desafío) Escribe una consulta SQL para seleccionar los order_id de la tabla orders que tengan un order_status diferente de 'delivered'. Carga el resultado en un DataFrame y muestra cuántas órdenes tienen un estado diferente.